In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

In [20]:
data = pd.read_csv('masterCSVfmfull.csv')

In [21]:
agg_suno_w = data.groupby('country')[['suicides_no', 'suicides/100k pop']].agg(['sum'])
agg_suno_w = agg_suno_w.reset_index()

In [22]:
agg_suno_w

                          country suicides_no suicides/100k pop
                                          sum               sum
0                         Albania      1970.0            924.76
1             Antigua and Barbuda        11.0            179.14
2                       Argentina     82219.0           3894.59
3                         Armenia      1905.0            976.21
4                           Aruba       101.0           1596.52
5                       Australia     70111.0           4677.41
6                         Austria     50073.0           9076.23
7                      Azerbaijan      1656.0            356.24
8                         Bahamas        93.0            344.28
9                         Bahrain       463.0            467.24
10                       Barbados       177.0            891.13
11                        Belarus     59892.0           7831.13
12                        Belgium     62761.0           7900.50
13                         Belize       348.0           2093.49
14         Bosnia and Herzegovina       318.0            110.81
15                         Brazil    226613.0           2174.72
16                       Bulgaria     36388.0           7016.08
17                     Cabo Verde        42.0            133.84
18                         Canada    107561.0           4338.72
19                          Chile     40895.0           3921.64
20                       Colombia     53080.0           2009.39
21                     Costa Rica      6792.0           2553.72
22                        Croatia     18429.0           5982.84
23                           Cuba     41418.0           6111.95
24                         Cyprus       412.0            586.26
25                 Czech Republic     43687.0           5952.99
26                        Denmark     15297.0           3721.65
27                       Dominica         0.0              0.00
28                        Ecuador     20660.0           2345.21
29                    El Salvador     11683.0           3035.94
..                            ...         ...               ...
71                    Puerto Rico      9043.0           3789.28
72                          Qatar       574.0            318.15
73              Republic of Korea    261730.0           9350.45
74                        Romania     72777.0           4171.55
75             Russian Federation   1209742.0          11305.13
76          Saint Kitts and Nevis         0.0              0.00
77                    Saint Lucia       230.0           2420.12
78   Saint Vincent and Grenadines       124.0           1726.63
79                     San Marino         4.0            145.62
80                         Serbia     24179.0           4787.45
81                     Seychelles        98.0           1615.70
82                      Singapore     10089.0           6340.98
83                       Slovakia     13437.0           3318.16
84                       Slovenia     10615.0           7012.62
85                   South Africa      7321.0            231.49
86                          Spain    100202.0           3509.06
87                      Sri Lanka     55641.0           4658.96
88                       Suriname      2166.0           7162.32
89                         Sweden     37795.0           5247.72
90                    Switzerland     26217.0           4794.07
91                       Thailand    110643.0           2362.67
92            Trinidad and Tobago      4039.0           4479.51
93                         Turkey     10131.0            199.17
94                   Turkmenistan      8624.0           2994.73
95                        Ukraine    319950.0           8931.66
96           United Arab Emirates       622.0             94.89
97                 United Kingdom    136805.0           2790.92
98                  United States   1034013.0           5140.97
99                        Uruguay     13138.0           6538.96
100                    Uzbekistan     34803.0           2138.17

[101 rows x 3 columns]

In [23]:
agg_suno_w.to_csv('Suma liczby i per100kpop dla kraju.csv')

In [24]:
data.columns

Index(['sex', 'country', 'year', 'age', 'generation', 'suicides_no',
       'population', 'suicides/100k pop', 'HDI for year', 'gdp_for_year ($) ',
       'gdp_per_capita ($)'],
      dtype='object')