In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

In [16]:
data = pd.read_csv('masterCSVfmfull.csv')

In [17]:
agg_pop = data.groupby('year')['population'].agg(['sum', 'mean', 'count'])
agg_pop = agg_pop.reset_index()

In [18]:
ftl1= (agg_pop['year'] != 2016)
agg_pop = agg_pop.loc[ftl1, ['year', 'sum', 'mean','count']]

In [19]:
agg_pop

    year           sum          mean  count
0   1985  1.008600e+09  1.751042e+06    576
1   1986  1.029910e+09  1.788038e+06    576
2   1987  1.095030e+09  1.689861e+06    648
3   1988  1.054094e+09  1.792678e+06    588
4   1989  1.225514e+09  1.963965e+06    624
5   1990  1.466620e+09  1.909662e+06    768
6   1991  1.489988e+09  1.940089e+06    768
7   1992  1.569539e+09  2.012230e+06    780
8   1993  1.530417e+09  1.962073e+06    780
9   1994  1.548749e+09  1.897977e+06    816
10  1995  1.591559e+09  1.700384e+06    936
11  1996  1.662268e+09  1.798991e+06    924
12  1997  1.702992e+09  1.843064e+06    924
13  1998  1.725181e+09  1.819812e+06    948
14  1999  1.776363e+09  1.783497e+06    996
15  2000  1.799228e+09  1.743438e+06   1032
16  2001  1.755565e+09  1.662467e+06   1056
17  2002  1.822153e+09  1.765652e+06   1032
18  2003  1.838458e+09  1.781452e+06   1032
19  2004  1.745247e+09  1.731395e+06   1008
20  2005  1.734910e+09  1.721141e+06   1008
21  2006  1.840909e+09  1.804813e+06   1020
22  2007  1.859564e+09  1.801903e+06   1032
23  2008  1.860621e+09  1.824138e+06   1020
24  2009  1.976228e+09  1.850401e+06   1068
25  2010  1.997297e+09  1.891380e+06   1056
26  2011  1.993362e+09  1.931553e+06   1032
27  2012  1.912812e+09  1.967914e+06    972
28  2013  1.890162e+09  1.968918e+06    960
29  2014  1.912057e+09  2.042796e+06    936
30  2015  1.774658e+09  2.385293e+06    744

In [20]:
agg_pop.to_csv('agg_pop.csv')

In [21]:
data.columns

Index(['sex', 'country', 'year', 'age', 'generation', 'suicides_no',
       'population', 'suicides/100k pop', 'HDI for year', 'gdp_for_year ($) ',
       'gdp_per_capita ($)'],
      dtype='object')